# 1. ОБЩИЙ ФОН ЭКРАНА
background {
    monitor =
    path = screenshot
    blur_passes = 0    
}

# 2. ВЕРХНЯЯ КАПСУЛА: ПОДЛОЖКА ЧАСОВ (Твой стиль)
shape {
    monitor =
    size = 550, 250
    rounding = 90      

    color = rgba(36, 39, 58, 0.25)
    border_size = 2
    border_color = rgba(255, 255, 255, 0.6)

    position = 0, 170
    halign = center
    valign = center
}

# 3. САМИ ДЕВОЧКИ-ЧАСЫ (Тот самый рабочий фикс против мыла)
image {
    monitor =
    path = /tmp/hyprlock_clock.png
    
    # СТРОГО ОДНО ЧИСЛО! Квадратный контейнер совпадает с размером PNG.
    # Это полностью отключает внутреннее сглаживание движка.
    size = 500
    
    rounding = 0       
    border_size = 0
    reload_time = 1

    position = 0, 170
    halign = center
    valign = center
    zindex = 1         
}

# 4. СКРЫТЫЙ СУПЕР-ТАЙМЕР (Не даёт времени стопиться)
label {
    monitor =
    text = cmd[update:1000] /home/nirx/.config/hypr/clock_girls/make_clock.sh
    color = rgba(0, 0, 0, 0.0)
    font_size = 1
    position = 0, 0
    halign = left
    valign = top
}

# 5. НИЖНЯЯ КАПСУЛА: ПОЛЕ ВВОДА ПАРОЛЯ (Твой стиль)
input-field {
    monitor =
    size = 330, 63
    outline_thickness = 2
    rounding = 40       
    
    outer_color = rgba(255, 255, 255, 0.6)
    inner_color = rgba(36, 39, 58, 0.25)
    font_color = rgb(255, 255, 255)
    
    blur_background = true
    blur_passes = 3
    blur_size = 7

    dots_size = 0.25
    dots_spacing = 0.3
    dots_center = true
    fade_on_empty = false
    
    placeholder_text = <span foreground="##8087a2" font_family="JetBrains Mono">Password...</span>
    hide_input = false
    
    position = 0, -40
    halign = center
    valign = center
}
